<?php

namespace AppBundle\Repository\blogusers;

/**
 * FOSUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FOSUserRepository extends \Doctrine\ORM\EntityRepository
{
}
